---
title: "Identifiers"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Identifiers}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The data provided by quincunx includes various identifiers. This document serves as a quick reference list for the identifers you might find in objects returned by quincunx functions.

Some of these identifiers are externally defined while others are created by quincunx to aid linking rows among tables. The external identifiers have global scope, i.e., their meaning is valid regardless of context, e.g., a PGS identifier is unique and always identifies the same polygenic score. Identifiers whose scope is local are surrogate IDs that help relating data observations across tables, and do not have any other special meaning outside the tables they appear (`sample_id`, `effect_size_id`, `classification_metrics_id` and `other_metrics_id`.)

| Variable                    | Name                            | Acronym | Scope  | Database source                                              |
| --------------------------- | ------------------------------- | ------- | ------ | ------------------------------------------------------------ |
| `pgs_id`, `child_pgs_id`    | Polygenic Score ID              | PGS     | global | [PGS Catalog](https://www.pgscatalog.org/)                   |
| `pgp_id`                    | Polygenic Publication ID        | PGP     | global | [PGS Catalog](https://www.pgscatalog.org/)                   |
| `pss_id`                    | PGS Catalog Sample Set ID       | PSS     | global | [PGS Catalog](https://www.pgscatalog.org/)                   |
| `ppm_id`                    | PGS Performance Metric ID       | PPM     | global | [PGS Catalog](https://www.pgscatalog.org/)                   |
| `efo_id`, `parent_efo_id`   | Experimental Factor Ontology ID | EFO     | global | [Experimental Factor Ontology](https://www.ebi.ac.uk/efo/)   |
| `pubmed_id`                 | PubMed ID                       | PMID    | global | [PubMed.gov](https://pubmed.ncbi.nlm.nih.gov/)               |
| `study_id`                  | GWAS Catalog Study ID           | GCST    | global | [GWAS Catalog](https://www.ebi.ac.uk/gwas/)                  |
| `rsID`                      | Reference SNP Cluster ID        | rsID    | global | [dbSNP](https://www.ncbi.nlm.nih.gov/snp/docs/RefSNP_about/) |
| `sample_id`                 | Sample ID                       |         | local  | Generated by quincunx.                                       |
| `effect_size_id`            | Effect Size ID                  |         | local  | Generated by quincunx.                                       |
| `classification_metrics_id` | Classification Metrics ID       |         | local  | Generated by quincunx.                                       |
| `other_metrics_id`          | Other Metrics ID                |         | local  | Generated by quincunx.                                       |

